apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 3
  template:
    metadata:
      annotations:
        eks.amazonaws.com/compute-type: ec2
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/compute-type
                operator: NotIn
                values:
                - fargate
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 99
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nginx
              topologyKey: topology.kubernetes.io/zone
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: init
        image: registry.k8s.io/nginx-slim:0.8
        command:
        - sh
        - -c
        - |
          set -euvx
          if [ -f /html-to-update/index.html ]
          then
            exit 0
          fi
          cp /usr/share/nginx/html/index.html /html-to-update/index.html
          sed -ri -e "s/nginx/nginx(pod_name:${POD_NAME})/g" /html-to-update/index.html
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
             fieldPath: "metadata.name"
        volumeMounts:
        - name: www
          mountPath: /html-to-update
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: csi-gp2
      resources:
        requests:
          storage: 1Gi
